[git_status]
show_sync_count = true
staged_count.enabled = true
conflicted_count.enabled = true
untracked_count.enabled = true
modified_count.enabled = true
renamed_count.enabled = true
deleted_count.enabled = true
